server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: myalias

spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: file-status-processor

  data:
    mongodb:
      uri: ${mongodb.uri}
      database: ${mongodb.database}

  cloud:
    stream:
      function:
        definition: statusEvent
      bindings:
        statusEvent-in-0:
          destination: ${kafka.topic.status}
          group: file-status-processor-group
          contentType: application/json
      kafka:
        binder:
          brokers: ${kafka.bootstrap-servers}
          configuration:
            spring.json.trusted.packages: '*'

management:
  endpoints:
    web:
      exposure:
        include: health, info, env