spring:
  application:
    name: file-processor
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    stream:
      function:
        definition: processValidation
      bindings:
        processValidation-in-0:
          destination: ${kafka.topic.upload}
          contentType: application/json
          consumer:
            use-native-decoding: false
        processValidation-out-0:
          destination: ${kafka.topic.status}
      kafka:
        binder:
          brokers: ${kafka.bootstrap-servers}
          configuration:
            spring.json.trusted.packages: '*'

server:
  port: 8081