spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: file-uploader
  cloud:
    stream:
      bindings:
        uploadEvents-out-0:
          destination: ${kafka.topic.upload}
        fileStatusEvents-out-0:
          destination: ${kafka.topic.status}
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers}

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - refresh
  endpoint:
    health:
      show-details: always
    env:
      access: unrestricted